/**************************************************************************\
 *
 *                      PDAOS Window System
 *
 * Copyright (c) 1998 by CASS Corporation & Software Engineering Center
 *                       All Rights Reserved
 *
 *
 * Filename     Calendar.h
 *
 * Purpose      Implements the Calendar application.
 *  
 * Author       ZhangYi && SunJie
 *
 *-------------------------------------------------------------------------*/

#define WM_CALENDAR			WM_USER + 100

extern BOOL DisplayCalendar(HWND, SYSTEMTIME);
