//#define IDQ_RING_HANGUP  WM_USER+101

#define WM_LIST_CALLS    WM_USER+102  
#define WM_VOICER_ANSWER  WM_USER+103
#define WM_DIAL_MACCALLBACK WM_USER+104
#define WM_VOICER_HANGUP     WM_USER+105
#define	WM_SWITCH_CALLLINE	WM_USER+106
#define	WM_CALLTIME_COUNT	WM_USER+107
#define	WM_SET_CALLWAITING	WM_USER+108
#define	WM_SWITCH_CUTALL	WM_USER+109
#define	WM_MUTE_CONTROL		WM_USER+110
#define	WM_DTMF_DATA		WM_USER+111
#define	WM_QRY_CALLWAITING	WM_USER+112
#define	WM_QRY_FWDCALL		WM_USER+113
#define	WM_QRY_CALLBARRING	WM_USER+114
#define	WM_SET_CALLBARRING	WM_USER+115
#define	WM_SET_OPRATOR		WM_USER+116
#define	WM_SEARCH_OPRATOR	WM_USER+117
#define	WM_CALL_AUTOANSWER	WM_USER+118
#define	WM_FWD_MSG			WM_USER+119
#define	WM_VOICE_DIAL		WM_USER+120
#define	WM_VOICEBOX_HANGUP	WM_USER+121
#define	WM_BREAKBOX_DIAL	WM_USER+122
#define	WM_LIST_UPDATE		WM_USER+123
#define WM_CALLING_HANGUP   WM_USER+124
#define WM_READ_PRE_NET_LIST WM_USER+125 

#define WM_VOICE_HANGUP_RIGHTDOWN MAKEWPARAM(WM_USER+11 ,0)
#define WM_VOICE_ANSWER_LEFTDOWN  MAKEWPARAM(WM_USER+12 ,1)

extern DWORD Ring_AppControl(HWND *MYHWND, int);
extern DWORD MBRing_AppControl(HWND *MYHWND, int);

#define MAX_COUNT 5