
#define    IDS_UI_URLCNTNULL                         1
#define    IDS_UI_COMFIRMDELETE                      2
#define    IDS_UI_COMFIRMPROMPT                      3
#define    IDS_UI_URLADDRESS                         4
#define    IDS_UI_BOOKMARKS                          5
#define    IDS_UI_OK                                 6
#define    IDS_UI_CANCEL                             7
#define    IDS_UI_USERDBERROR                        8
#define    IDS_UI_ERROR                              9
#define    IDS_UI_ADDBOOKMARK                       10
#define    IDS_UI_TITLE                             11
#define    IDS_UI_INPUTTITLE                        12
#define    IDS_UI_BOOKMARKFULL                      13
#define    IDS_UI_BOOKMARKSMANAGE                   14
#define    IDS_UI_ADDRESS                           15
#define    IDS_UI_CLOSE                             16
#define    IDS_UI_UP                                17
#define    IDS_UI_DOWN                              18
#define    IDS_UI_MODIFY                            19
#define    IDS_UI_DELETE                            20
#define    IDS_UI_MODIFYTITLE                       21
#define    IDS_UI_USERNAME                          22
#define    IDS_UI_USERPASSWORD                      23
#define    IDS_UI_MODIFYPASSWORD                    24
#define    IDS_UI_CANNOTLOGIN                       25
#define    IDS_UI_LOGINFAIL                         26
#define    IDS_UI_PASSWORDERROR                     27
#define    IDS_UI_GETNEWPASSWORDFAIL                28
#define    IDS_UI_START                             29
#define    IDS_UI_DOWNLOADFILE                      30
#define    IDS_UI_NOWFINISH                         31
#define    IDS_UI_OLDPASSWORD                       32
#define    IDS_UI_NEWPASSWORD                       33
#define    IDS_UI_CONFIRMPASSWORD                   34
#define    IDS_UI_OLDPASSWORDERROR                  35
#define    IDS_UI_NEWPASSWORDDISMATCH               36
#define    IDS_UI_MODIFYPASSWORDOK                  37
#define    IDS_UI_FINISH                            38
#define    IDS_UI_MODIFYPASSWORDFAIL                39
#define    IDS_UI_NOTLOGIN                          40
#define    IDS_UI_NOPAGE                            41
#define    IDS_UI_CURRENTPAGE                       42
#define    IDS_UI_SAVEPAGE                          43
#define    IDS_UI_ADD                               44
#define    IDS_UI_OPEN                              45
#define    IDS_UI_PAGEUSERFREE                      46
#define    IDS_UI_CURRENTPAGESIZE                   47
#define    IDS_UI_NOENOUGHFREESPACE                 48
#define    IDS_UI_ERRORMESSAGE                      49
#define    IDS_UI_NOENOUGHFREEITEM                  50
#define    IDS_UI_NOPAGETOSAVE                      51
#define    IDS_UI_SAVEPAGEFAIL                      52
#define    IDS_UI_NOOPENINDEX                       53
#define    IDS_UI_NODELETEINDEX                     54
#define    IDS_UI_UPDATEURL                         55
#define    IDS_UI_INPUTXINDEX                       56
#define    IDS_UI_HOMEPAGEURL                       57
#define    IDS_UI_NOACTION                          58
#define    IDS_UI_DIALUPFIRST                       59
#define    IDS_UI_IMPORT                            60
#define    IDS_UI_ERRORPROMPT                       61
#define    IDS_UI_WINDOWFAIL                        62
#define    IDS_UI_EDITFAIL                          63
#define    IDS_UI_STATUSBARFAIL                     64
#define    IDS_UI_TOOLBARFAIL                       65
#define    IDS_UI_MENUFAIL                          66
#define    IDS_UI_MENUFONTFAIL                      67
#define    IDS_UI_S_STACKOVERFLOW                   68
#define    IDS_UI_S_STACKEMPT                       69
#define    IDS_UI_P_STACKOVERFLOW                   70
#define    IDS_UI_P_STACKEMPT                       71
#define    IDS_UI_V_STACKOVERFLOW                   72
#define    IDS_UI_V_STACKEMPT                       73
#define    IDS_UI_O_STACKOVERFLOW                   74
#define    IDS_UI_O_STACKEMPT                       75
#define    IDS_UI_KB_REGWINDOWFAIL                  76
#define    IDS_UI_KB_CREWINDOWFAIL                  77
#define    IDS_UI_KB_OPENINIFAIL                    78
#define    IDS_UI_REGFILEFAIL                       79
#define    IDS_UI_NOMEMORY                          80
#define    IDS_UI_KB_DATAFAIL                       81
#define    IDS_UI_NOKEYCODE                         82
#define    IDS_UI_DLB_CREATEFAIL                    83
#define    IDS_UI_DLB_NOMEMORY                      84
#define    IDS_UI_DLB_CRECONTROLFAIL                85
#define    IDS_UI_UDBERROR                          86
#define    IDS_UI_BROWSERERROR                      87
#define    IDS_UI_DNL_REGISTEFAIL                   88
#define    IDS_UI_DNL_CREATEFAIL                    89
#define    IDS_UI_DNL_CRECONTROLFAIL                90
#define    IDS_UI_DNL_CREDCFAIL                     91
#define    IDS_UI_DNL_CREPENFAIL                    92
#define    IDS_UI_DNL_CREBRUSHFAIL                  93
#define    IDS_UI_DATAIN                            94
#define    IDS_UI_DONE                              95
#define    IDS_UI_IPNOTFOUND                        96
#define    IDS_UI_CONNECTMESSAGE                    97
#define    IDS_UI_IPCONNECTFAIL                     98
#define    IDS_UI_SERVERCHANGE                      99
#define    IDS_UI_SERVERERROR                      100
#define    IDS_UI_FILEERROR                        101
#define    IDS_UI_MEDIATYPEERROR                   102
#define    IDS_UI_FOUND                            103
#define    IDS_UI_LOOKUPIP                         104
#define    IDS_UI_CONNECT                          105
#define    IDS_UI_UPDATEFILEERROR                  106
#define    IDS_UI_UPDATEMESSAGE                    107
#define    IDS_UI_STARTUPOK                        108
#define    IDS_SCRIPT_ERRORPOS                     109
#define    IDS_SCRIPT_LINE                         110
#define    IDS_SCRIPT_MARKNO                       111
#define    IDS_SCRIPT_STATUS                       112
#define    IDS_SCRIPT_MARK                         113
#define    IDS_SCRIPT_ERROR                        114
#define    IDS_UDB_OPRFAIL                         115
#define    IDS_UDB_FILEERROR                       116
#define    IDS_UDB_FILEFAIL                        117
#define    IDS_UDB_OPENED                          118
#define    IDS_UDB_OPEN_NOHANDLE                   119
#define    IDS_UDB_OPEN_NORAM                      120
#define    IDS_UDB_NOTFOUND                        121
#define    IDS_UDB_RECORD_NOTFOUND                 122
#define    IDS_UDB_CLOSED                          123
#define    IDS_UDB_EXIST                           124
#define    IDS_UDB_FIELD_NOTFOUND                  125
#define    IDS_UDB_FIELD_INCOMPATIBLE              126
#define    IDS_UDB_ACCESS_DENIED                   127
#define    IDS_UDB_RECORD_DELETED                  128
#define    IDS_UDB_RECEIVE_EMPTY                   129
#define    IDS_UDB_DATA_EMPTY                      130
#define    IDS_UDB_NO_FIELD                        131
#define    IDS_UDB_FIELD_ILLEGAL                   132
#define    IDS_UDB_FIELD_EXIST                     133
#define    IDS_UDB_RECORD_FULL                     134
#define    IDS_UDB_FIELD_FULL                      135
#define    IDS_UDB_MARKEXIST                       136
#define    IDS_UDB_IMPORTPROMPT                    137
#define    IDS_UDB_MACSET                          138
#define    IDS_UDB_MACINFO                         139
#define    IDS_UDB_MACNAME                         140
#define    IDS_UDB_LOCALADDR                       141
#define    IDS_UDB_SUBMASK                         142
#define    IDS_UDB_DEFAULT                         143
#define    IDS_UDB_DOMAIN                          144
#define    IDS_UDB_PRIMARYDNS                      145
#define    IDS_UDB_SECONDDNS                       146
#define    IDS_UDB_NETNUM1                         147
#define    IDS_UDB_MASK1                           148
#define    IDS_UDB_GATEWAY1                        149
#define    IDS_UDB_NETNUM2                         150
#define    IDS_UDB_MASK2                           151
#define    IDS_UDB_GATEWAY2                        152
#define    IDS_UDB_NETNUM3                         153
#define    IDS_UDB_MASK3                           154
#define    IDS_UDB_GATEWAY3                        155
#define    IDS_UDB_DHCP                            156
#define    IDS_UDB_SETPRIMARYSELECT                157
#define    IDS_UDB_OK                              158
#define    IDS_UDB_CANCEL                          159
#define    IDS_UDB_RESET                           160
#define    IDS_UDB_PROMPT                          161
#define    IDS_UDB_SAVECHANGE                      162
#define    IDS_UDB_PRIMARYSELECT                   163
#define    IDS_UDB_DOMAINVALID                     164
#define    IDS_UDB_INPUTVALID                      165
#define    IDS_UDB_INPUTAGAIN                      166
#define    IDS_UDB_PROXYSET                        167
#define    IDS_UDB_SETPRIMARYPROXY                 168
#define    IDS_UDB_PROXYMODIFY                     169
#define    IDS_UDB_PROXYDELETE                     170
#define    IDS_UDB_PROXYADD                        171
#define    IDS_UDB_PROXYSELECT                     172
#define    IDS_UDB_USEPROXY                        173
#define    IDS_UDB_EDITPROXY                       174
#define    IDS_UDB_PROXYNAME                       175
#define    IDS_UDB_PROXYADDR                       176
#define    IDS_UDB_PROXYPORT                       177
#define    IDS_UDB_PROXYUSERNAME                   178
#define    IDS_UDB_PROXYPASSWORD                   179
#define    IDS_UDB_PROXYEXCLUDEADDR                180
#define    IDS_UDB_SELECTFIRST                     181
#define    IDS_UDB_NORECORDTOMODIFY                182
#define    IDS_UDB_NORECORDTODELETE                183
#define    IDS_UDB_CANNOTDELETE                    184
#define    IDS_UDB_SUREDELETE                      185
#define    IDS_UDB_FIELDEMPT                       186
#define    IDS_UDB_PROXYEXIST                      187
#define    IDS_UDB_CURRENTPROXY                    188
#define    IDS_DB_RECORDFULL                       189
#define    IDS_UDB_NETWORKCARDSET                  190
#define    IDS_UDB_NETWORKCARDINFO                 191
#define    IDS_UDB_INTERRUPT                       192
#define    IDS_UDB_BASEADDR                        193
#define    IDS_UDB_PSETPRIMARY                     194
#define    IDS_CGISETUP_CONFIRMDELETE              195
#define    IDS_CGISETUP_PROMPT                     196
#define    IDS_CGISETUP_MAILNAMEEXISTED            197
#define    IDS_CGISETUP_USERNAMEEXISTED            198
#define    IDS_CGISETUP_ISPEXISTED                 199
#define    IDS_CGISETUP_ERRMESSAGE                 200
#define    IDS_CGISETUP_CANNOTBENULL               201
#define    IDS_CGISETUP_INPUTINVALID               202
#define    IDS_CGISETUP_TOOSMALL                   203
#define    IDS_CGISETUP_TOOBIG                     204
#define    IDS_CGISETUP_PROXYBUSY                  205
#define    IDS_CGISETUP_AUTODELETE                 206
#define    IDS_CGISETUP_USEMAILDELETE              207
#define    IDS_UPDATE_IMGOFDOMAIN                  208
#define    IDS_UPDATE_UPDATEONLINE                 209
#define    IDS_UPDATE_CONTINUE                     210
#define    IDS_UPDATE_STOP                         211
#define    IDS_UPDATE_CANCEL                       212
#define    IDS_UPDATE_IMGOFADDRESS                 213
#define    IDS_UPDATE_TRANSDATAERR                 214
#define    IDS_UPDATE_UPDATEEXIT                   215
#define    IDS_UPDATE_IMGOFTRSDATA                 216
#define    IDS_UPDATE_CHECK                        217
#define    IDS_UPDATE_UPDATEERROR                  218
#define    IDS_UPDATE_WRITEFLASH                   219
#define    IDS_UPDATE_STOSTOPCTOEXIT               220
#define    IDS_UPDATE_BEGANTOTRSDATE               221
#define    IDS_UPDATE_NNKWSIZE                     222
#define    IDS_UPDATE_RECEIVEDATE                  223
#define    IDS_UPDATE_ENDTRSDATA                   224
#define    IDS_UPDATE_UTOUPDATE                    225
#define    IDS_UPDATE_UPDATE                       226
#define    IDS_UPDATE_FINDADDFAL                   227
#define    IDS_UPDATE_CONSERVERFAL                 228
#define    IDS_UPDATE_CLIENTERR                    229
#define    IDS_UPDATE_SERVERERR                    230
#define    IDS_PRINT_TITLE                         231
#define    IDS_UPDATE_FINDINGADD                   232
#define    IDS_UPDATE_CONNECTING                   233
#define    IDS_UPDATE_WAITTINGDATE                 234
#define    IDS_PRINT_INFO                          235
#define    IDS_UPDATE_UPDATEMESSAGE                236
#define    IDS_UPDATE_ABOUTUPDATE                  237
#define    IDS_PRINT_OFFLINE                       238
#define    IDS_PRINT_OFFLINERETRY                  239
#define    IDS_PRINT_NOPAPER                       240
#define    IDS_PRINT_ERROR                         241
#define    IDS_MAIL_SER                            242
#define    IDS_MAIL_RER                            243
#define    IDS_UNARJ_UNZIP                         244
#define    IDS_DEFDIAL_PROMPT                      245
#define    IDS_DEFDIAL_OK                          246
#define    IDS_DEFDIAL_CANCAL                      247
#define    IDS_DEFDIAL_IPW                         248
#define    IDS_DEFDIAL_MPW                         249
#define    IDS_DEFDIAL_CLOSE                       250
#define    IDS_DEFDIAL_ISPNAME                     251
#define    IDS_DEFDIAL_USENAME                     252
#define    IDS_DEFDIAL_PASSWORD                    253
#define    IDS_DEFDIAL_ADD                         254
#define    IDS_DEFDIAL_DELETE                      255
#define    IDS_DEFDIAL_MODIFY                      256
#define    IDS_DEFDIAL_SAVE                        257
#define    IDS_DEFDIAL_ISPL                        258
#define    IDS_DEFDIAL_PHONE                       259
#define    IDS_DEFDIAL_PDNS                        260
#define    IDS_DEFDIAL_SDNS                        261
#define    IDS_DEFDIAL_NPASSWORD                   262
#define    IDS_DEFDIAL_CPASSWORD                   263
#define    IDS_DEFDIAL_TWPASSERR                   264
#define    IDS_DEFDIAL_ERROR                       265
#define    IDS_DEFDIAL_MPASSFAL                    266
#define    IDS_DEFDIAL_FMPASS                      267
#define    IDS_DEFDIAL_PASSERR                     268
#define    IDS_DEFDIAL_ISPCBNULL                   269
#define    IDS_DEFDIAL_ADDISPFAL                   270
#define    IDS_DEFDIAL_DELISPFAL                   271
#define    IDS_DEFDIAL_MODISPFAL                   272
#define    IDS_DEFDIAL_USERCBNULL                  273
#define    IDS_DEFDIAL_PHONECBNULL                 274
#define    IDS_DEFDIAL_CONFIRMDEL                  275
#define    IDS_DEFDIAL_ISPEXIST                    276
#define    IDS_SETVIDEO_OK                         277
#define    IDS_SETVIDEO_CANCAL                     278
#define    IDS_SETVIDEO_SETLTCT                    279
#define    IDS_SETVIDEO_SETLIGHTNESS               280
#define    IDS_SETVIDEO_SETCONTRAST                281
#define    IDS_SETVIDEO_COMEBACK                   282
#define    IDS_SETVIDEO_APPLY                      283
#define    IDS_SETVIDEO_PREVIEW                    284
#define    IDS_SETVIDEO_REFRESH                    285
#define    IDS_DEFMAIL_MBOXNULL                    286
#define    IDS_DEFMAIL_UNAMENULL                   287
#define    IDS_DEFMAIL_PWDNULL                     288
#define    IDS_DEFMAIL_SMTPNULL                    289
#define    IDS_DEFMAIL_POP3NULL                    290
#define    IDS_DEFMAIL_RETRUNNULL                  291
#define    IDS_DEFMAIL_ERROR                       292
#define    IDS_DEFMAIL_RECFULL                     293
#define    IDS_DEFISP_NAMENULL                     294
#define    IDS_DEFISP_UNAMENULL                    295
#define    IDS_DEFISP_PWDNULL                      296
#define    IDS_DEFISP_TELNULL                      297
#define    IDS_DEFISP_ERROR                        298
#define    IDS_DEFISP_RECFULL                      299
#define    IDS_CGISETUP_OK                         300
#define    IDS_CGISETUP_CANCLE                     301
#define    IDS_CGISETUP_ISPNAME                    302
#define    IDS_CGISETUP_USERNAME                   303
#define    IDS_CGISETUP_PASSWORD                   304
#define    IDS_CGISETUP_SETUPISP                   305
#define    IDS_CGISETUP_TELPHONE                   306
#define    IDS_CGISETUP_SETUPMAIL                  307
#define    IDS_CGISETUP_MAILBOX                    308
#define    IDS_CGISETUP_LOGINUSERNAME              309
#define    IDS_CGISETUP_LOGINPASSWORD              310
#define    IDS_CGISETUP_POP3SERVER                 311
#define    IDS_CGISETUP_SMTPSERVER                 312
#define    IDS_CGISETUP_ADDRESS                    313
#define    IDS_CGISETUP_SETUPISPCONT               314
#define    IDS_CGISETUP_SETUPMAILCONT              315
#define    IDS_CGISETUP_DEFISPNAME                 316
#define    IDS_UDB_MUSTFILL                        317
#define    IDS_UI_GOTO                             318
#define    IDS_UI_COMFIRMDELETEPAGE                319
#define    IDS_CGISETUP_LOGIN                      320
#define    IDS_UI_ABOUT1                           321
#define    IDS_UI_ABOUT2                           322
#define    IDS_UDB_DBFILEERROR                     323
#define    IDS_UDB_VERSION                         324
#define    IDS_UDB_FILENOUSE                       325
#define    IDS_UI_FAVORITEDBERROR                  326
#define    IDS_UI_LOGINNOT                         327
#define    IDS_STB_ABOUT                           328
#define    NAME_OF_IN_BOX                          329
#define    NAME_OF_OUT_BOX                         330
#define    NAME_ATTACHMENT                         331
#define    DIAL_MSG01                              332
#define    DIAL_MSG02                              333
#define    DIAL_MSG03                              334
#define    DIAL_MSG04                              335
#define    DIAL_MSG05                              336
#define    DIAL_MSG06                              337
#define    DIAL_MSG07                              338
#define    DIAL_MSG08                              339
#define    DIAL_MSG09                              340
#define    DIAL_MSG10                              341
#define    DIAL_MSG11                              342
#define    DIAL_MSG12                              343
#define    DIAL_MSG13                              344
#define    DIAL_MSG14                              345
#define    DIAL_MSG15                              346
#define    DIAL_MSG16                              347
#define    DIAL_MSG17                              348
#define    DIAL_MSG18                              349
#define    DIAL_MSG20                              350
#define    DIAL_MSG21                              351
#define    DIAL_MSG22                              352
#define    DIAL_MSG23                              353
#define    DIAL_MSG24                              354
#define    DIAL_MSG25                              355
#define    DIAL_MSG26                              356
#define    DIAL_MSG30                              357
#define    DIAL_MSG31                              358
#define    DIAL_MSG32                              359
#define    DIAL_MSG33                              360
#define    DIAL_MSG34                              361
#define    DIAL_MSG35                              362
#define    DIAL_MSG36                              363
#define    DIAL_MSG37                              364
#define    DIAL_MSG38                              365
#define    DIAL_MSG39                              366
#define    DIAL_MSG40                              367
#define    DIAL_MSG41                              368
#define    DIAL_MSG42                              369
#define    IDS_IME_ENG                             370
#define    IDS_IME_AERA                            371
#define    IDS_WIN_OK                              372
#define    IDS_WIN_CANCEL                          373
#define    IDS_WIN_YES                             374
#define    IDS_WIN_NO                              375
#define    IDS_WIN_IGNORE                          376
#define    IDS_WIN_RETRY                           377
#define    IDS_WIN_ABORT                           378
#define    IDZ_RES_NOERR                           379
#define    IDZ_RES_FILEERROR                       380
#define    IDZ_RES_MEMNO                           381
#define    IDZ_RES_NOFINDISP                       382
#define    IDZ_RES_ERRFORMAIL                      383
#define    IDZ_RES_REMAILERR                       384
#define    IDZ_RES_ATTACHERR                       385
#define    IDZ_RES_DATAERR                         386
#define    IDZ_RES_MAILFOLDERR                     387
#define    IDZ_RES_USERERR                         388
#define    IDZ_RES_MEMORYERR                       389
#define    IDZ_RES_MAILNOTFOUNDERR                 390
#define    IDZ_RES_TRANSFERERR                     391
#define    IDZ_RES_PASSWORDERR                     392
#define    IDZ_RES_USERNAMEERR                     393
#define    IDZ_RES_MAILERRINFO                     394
#define    IDZ_RES_MAILMOVEERR                     395
#define    IDZ_RES_MAILRERADDERROR                 396
#define    IDZ_RES_NOFOUNDMAILSERVER               397
#define    IDS_UI_PROXYUSERPASSWORD                398
#define    IDS_UI_NOTPRIVILEGE                     399
#define    IDS_UI_WAITING                          400
#define    DIAL_MSG43                              401
#define    DIAL_MSG44                              402
#define    DIAL_MSG45                              403
#define    DIAL_MSG50                              404
#define    DIAL_MSG51                              405
#define    DIAL_MSG52                              406
#define    DIAL_MSG53                              407
#define    DIAL_MSG54                              408
#define    IDS_UDB_CANNOTBENULL                    409
#define    DIAL_MSG60                              410
#define    DIAL_MSG61                              411
#define    DIAL_MSG62                              412
#define    DIAL_MSG63                              413
#define    DIAL_MSG64                              414
#define    DIAL_MSG46                              415
#define    IDS_MAIL_SUBJECT                        416
#define    IDS_MAIL_DATE                           417
