/***************************************************************************
 *
 *                      Pollex Mobile Platform
 *
 * Copyright (c) 2004 by Pollex Mobile Software Co., Ltd. 
 *                       All Rights Reserved 
 *
 * Module   : 
 *
 * Purpose  : 
 *
\**************************************************************************/
#include "str_mb_plx.h"

typedef struct 
{
    unsigned int iStrID;
    unsigned char * MB_strChn;
    unsigned char * MB_strEng;
}MBSTRING;

const MBSTRING MB_str[] =
{
    {STR_MBRECORD_ERROR1            ,"创建窗口失败"                     ,"Create Window Failed"}, 
    {STR_MBRECORD_PUB_ACTIVATE      ,"激活"                             ,"activate"},                                           
    {STR_MBRECORD_PUB_CANCEL        ,"取消"                             ,"cancel"},  
    {STR_MBRECORD_PUB_DEACTIVATE    ,"撤销"                             ,"deactivate"},                                        
    {STR_MBRECORD_DURATION          ,"通话计时"                         ,"Time"                                                        },
    {STR_MBRECORD_CLEAR             ,"清空"                             ,"Clear"                                                                },
    {STR_MBRECORD_LASTTIME          ,"上次通话"                         ,"Last Call"                                                            },
    {STR_MBRECORD_OUTCOUNT          ,"累计呼出"                         ,"Dialled"                                                               },
    {STR_MBRECORD_INCOUNT           ,"累计接入"                         ,"Received"                                                               },
    {STR_MBRECORD_TOTAL             ,"计时总计"                         ,"Total"                                                                },
    {STR_MBRECORD_DEL_UNANSWER      ,"未接电话"                         ,"Missed Calls"                                                             },
    {STR_MBRECORD_DEL_ANSWER        ,"已接电话"                         ,"Received Calls"                                                               },
    {STR_MBRECORD_DEL_DIAL          ,"已拨电话"                         ,"Dialled Numbers"                                                               },
    {STR_MBRECORD_DEL_ALL           ,"所有电话"                         ,"All Calls"                                                        },
    {STR_MBRECORD_DEL_CLEW          ,"系统将清空全部通话记录,是否继续?" ,"Delete all calls, continue or not?"                           },
    {STR_MBRECORD_DEL_FAIL          ,"删除失败"                         ,"Fail to delete"                                                          },
    {STR_MBRECORD_DEL_SUCC          ,"删除成功"                         ,"Delete successfully"                                                       },
    {STR_MBRECORD_LIST_DELONE       ,"是否删除?"                        ,"Delete or not?"                                                             },
    {STR_MBRECORD_LIST_DELALL       ,"是否删除?"                        ,"Delete or not?"                                                             },
    {STR_MBRECORD_LIST_VIEW         ,"查看"                             ,"View"                                                                 },
    {STR_MBRECORD_LIST_TIME         ,"时间序"                           ,"Time"                                                                 },
    {STR_MBRECORD_LIST_NAME         ,"人名序"                           ,"Name"                                                                 },
    {STR_MBRECORD_LIST_PICKUP       ,"提取到"                           ,"Pickup"                                                               },
    {STR_MBRECORD_LIST_PHONE        ,"电话"                             ,"Call"                                                                  },
    {STR_MBRECORD_LIST_LINKMAN      ,"联系人"                           ,"Address"                                                              },
    {STR_MBRECORD_LIST_SMS          ,"短信"                             ,"SMS"                                                                  },
    {STR_MBRECORD_LIST_MMS          ,"彩信"                             ,"MMS"                                                                  },
    {STR_MBRECORD_LIST_DELETE       ,"删除"                             ,"Erase"                                                               },
    {STR_MBRECORD_LIST_DELETEONE    ,"本条记录"                         ,"One"                                                                  },
    {STR_MBRECORD_LIST_DELETEALL    ,"全部记录"                         ,"All"                                                                  },
    {STR_MBRECORD_RECORD_CAPTION    ,"通话记录"                         ,"Record"                                                        },
    {STR_MBRECORD_TIMER             ,"通话计时"                         ,"Call Duration"                                                        },
    {STR_MBRECORD_DELETE_RECORD     ,"删除记录"                         ,"Erase Lists"                                                      },
    {STR_MBRECORD_SHIKE             ,"时间"                             ,"Time"                                                                 },
    {STR_MBRECORD_NUM               ,"号码"                             ,"NO."                                                                  },
    {STR_MBRECORD_NAME              ,"联系人"                           ,"Name"                                                                 },
    {STR_MBRECORD_UNKNOWN           ,"未知"                             ,"Unknown"                                                               },
    {STR_MBRECORD_DURATIONVIEW      ,"计时"                             ,"Clock"                                                                 },
    {STR_MBPHONE_GSM_CAPTION        ,"GSM操作"                          ,"GSM operation"                                                        },
    {STR_MBPHONE_GSM_SUCC           ,"成功"                             ,"success"                                                              },
    {STR_MBPHONE_GSM_FAIL           ,"失败"                             ,"fail"                                                                 },
    {STR_MBPHONE_GSM_FIND           ,"查询"                             ,"search"                                                                 },
    {STR_MBPHONE_GSM_HAVE           ,"已"                               ,"have"                                                                 },
    {STR_MBPHONE_GSM_IMEIFAIL       ,"IMEI查询失败"                     ,"Fail to find IMEI"                                                       },
    {STR_MBPHONE_GSM_PIN1_MODIFY    ,"修改pin1码%s"                     ,"Change PIN1 %s"                                                       },
    {STR_MBPHONE_GSM_PIN2_MODIFY    ,"修改pin2码%s"                     ,"Change PIN2 %s"                                                       },
    {STR_MBPHONE_GSM_PUK1_MODIFY    ,"PIN解锁%s"                        ,"Unlock PIN %s"                                                       },
    {STR_MBPHONE_GSM_PUK2_MODIFY    ,"PIN2解锁%s"                       ,"Unlock PIN2 %s"                                                       },
    {STR_MBPHONE_GSM_BARRING_MODIFY ,"注册网络密码%s"                   ,"Registration of net password %s"                                                },
    {STR_MBPHONE_GSM_FORWARD1       ,"所有呼叫转移"                     ,"all call forwarding"                                              },
    {STR_MBPHONE_GSM_FORWARD2       ,"所有条件转移"                     ,"all conditional call forwarding"                                      },
    {STR_MBPHONE_GSM_FORWARD3       ,"无条件转移"                       ,"call forwarding unconditional"                                       },
    {STR_MBPHONE_GSM_FORWARD4       ,"无应答转移"                       ,"call forwarding on no answer"                                        },
    {STR_MBPHONE_GSM_FORWARD5       ,"不在服务区或关机转移"             ,"call forwarding on not reachable"                            },
    {STR_MBPHONE_GSM_FORWARD6       ,"遇忙转移"                         ,"call forwarding busy"                                               },
    {STR_MBPHONE_GSM_BARRING1       ,"限制所有拨出电话"                 ,"call barring of outgoing call"                                          },
    {STR_MBPHONE_GSM_BARRING2       ,"解除所有通话限制"                 ,"all barring service (only for deactivation)"                               },
    {STR_MBPHONE_GSM_BARRING3       ,"限制所有拨出国际长途"             ,"call barring of outgoing international call"              },
    {STR_MBPHONE_GSM_BARRING4       ,"限制所有拨出国际长途{除本国}"     ,"call barring of outgoing international calls except to HPLMN"},
    {STR_MBPHONE_GSM_BARRING5       ,"解除所有拨出限制"                 ,"all outgoing barring service (only for deactivation)"},
    {STR_MBPHONE_GSM_BARRING6       ,"限制所有拨入电话"                 ,"call barring of incoming calls"},
    {STR_MBPHONE_GSM_BARRING7       ,"限制国际漫游时来电"               ,"call barring of incoming calls if roaming"},
    {STR_MBPHONE_GSM_BARRING8       ,"解除所有拨入限制"                 ,"all incoming barring service (only for deactivation)"                               },
    {STR_MBPHONE_GSM_CALLWAIT       ,"呼叫等待"                         ,"Call waiting"                                                   },
    {STR_MBPHONE_GSM_CLIR           ,"主叫号码显示限制%s%s"             ,"Calling Line Identification Restriction %s %s"                                                    },
    {STR_MBPHONE_CALLONEEND         ,"通话结束"                         ,"Call ended"                                                             },
    {STR_MBPHONE_CALLING            ,"通话"                             ,"Connected"                                                             },
    {STR_MBPHONE_HOLDING            ,"保持"                             ,"Hold"                                                                 },
    {STR_MBPHONE_RESTORE            ,"激活"                             ,"Unhold"                                                               },
    {STR_MBPHONE_HANGUP             ,"挂 断"                            ,"Hangup"                                                               },
    {STR_MBPHONE_HANGUP_CURRENT     ,"挂断当前通话?"                    ,"Hangup the call?"                                                     },
    {STR_MBPHONE_SWITCH_FAIL        ,"切换失败"                         ,"Fail to switch"                                                          },
    {STR_MBPHONE_ACTIVE_FAIL        ,"激活失败"                         ,"Fail to active"                                                          },
    {STR_MBPHONE_HANGUP_FAIL        ,"挂断失败"                         ,"Fail to hangup"                                                          },
    {STR_MBPHONE_SWITCH             ,"切换"                             ,"Switch"                                                               },
    {STR_MBPHONE_ACTIVEALL          ,"加入电话会议"                     ,"Add Meeting"                                                       },
    {STR_MBPHONE_HOLDINGALL         ,"全部保持"                         ,"All hold"                                                             },
    {STR_MBPHONE_HANGUPALL          ,"所有通话"                         ,"All calls"                                                           },
    {STR_MBPHONE_LINKING_CAPTION    ,"连接中"                           ,"Calling"                                                              },
    {STR_MBPHONE_BUSY               ,"线路忙"                           ,"Line is busy"                                                         },
    {STR_MBPHONE_DIAL_CAPTION       ,"呼叫"                             ,"Call"                                                                 },
    {STR_MBPHONE_SAVE               ,"保存"                             ,"Save"                                                                 },
    {STR_MBPHONE_DELETE             ,"删除"                             ,"Delete"                                                               },
    {STR_MBPHONE_ENERGENT           ,"只能进行紧急呼叫!"                ,"Only emergent call!"                                                  },
    {STR_MBPHONE_CALLCOMING         ,"来电"                             ,"Incoming"                                                             },
    {STR_MBPHONE_GET                ,"接听"                             ,"Get"                                                                  },
    {STR_MBPHONE_REPLACE            ,"替换"                             ,"Replace"                                                              },
    {STR_MBPHONE_CLEW               ,"提示"                             ,"Prompt"                                                                 },
    {STR_MBPHONE_HANGUP_ALL         ,"全部挂断?"                        ,"All hangup?"                                                          },
    {STR_MBPHONE_HALT               ,"连接中断"                         ,"Halt"},
    {STR_MBPHONE_HANGUPFAIL         ,"挂断失败"                         ,"Failed to hangup"},
    {STR_MBPHONE_WAIT               ,"请稍等"                           ,"Please wait"},
    {STR_MBPHONE_PBLIST_WITHOUTDATA ,"无记录"                           ,"Invalid location"},
    {STR_MBPHONE_DIALCLEW           ,"不能再拨号了"                     ,"Can't dialup"},
    {STR_MBPHONE_HEADPHONE          ,"调整音量"                         ,"Modify volume"},
    {STR_MBPHONE_MUTEFAIL           ,"静音失败"                         ,"Mute fail"},
    {STR_MBPHONE_UNMUTEFAIL         ,"解静音失败"                       ,"Unmute fail"},
    {STR_MBPHONE_MUTE               ,"静音"                             ,"Mute"},
    {STR_MBPHONE_UNMUTE             ,"发音"                             ,"Unmute"},
    {STR_MBPHONE_SMS                ,"短信"                             ,"SMS"},
    {STR_MBPHONE_MMS                ,"彩信"                             ,"MMS"},
    {STR_MBPHONE_ANSWER_FAIL        ,"接听失败"                         ,"Answer fail"},
    {STR_MBRECORD_COST              ,"通话计费"                         ,"Cost"},
    {STR_MBRECORD_SETUPCOST         ,"话费设定"                         ,"Setup Cost"},
    {STR_MBRECORD_BUTTONTXT_LAST    ,"最后通话清零"                     ,"Clear last"},
    {STR_MBRECORD_BUTTONTXT_TOTAL   ,"累计费用清零"                     ,"Clear total"},
    {STR_MBRECORD_CLEWTXT_LAST      ,"最后通话:"                        ,"Last:"},
    {STR_MBRECORD_CLEWTXT_TOTAL     ,"累计费用:"                        ,"Total:"},
    {STR_MBRECORD_VALIDPIN2         ,"验证PIN2码"                       ,"Invald Pin2"},
    {STR_MBRECORD_CLEWPIN2          ,"请输入PIN2码"                     ,"Input Pin2"},
    {STR_MBRECORD_VALIDPIN2FAIL     ,"PIN2码验证失败"                   ,"PIN valid fail"},
    {STR_MBPHONE_GSM_CLIP           ,"主叫号码显示%s%s"                 ,"Calling Line Identification Presentation %s %s"},
    {STR_MBPHONE_MULTHANGUP_ACTIVE  ,"只能挂断激活的通话"               ,"Hangup active call"},
    {STR_MBPHONE_GSM_UNLOCKPS       ,"手机锁解锁%s"                     ,"Unlock PS %s"},
    {STR_MBRECORD_PUB_RA            ,"注册激活"                         ,"register and activate"},
    {STR_MBRECORD_PUB_UD            ,"注销禁止"                         ,"unregistered and deactivate"},
    {STR_MBPHONE_GSM_COLP           ,"被接线路识别显示%s%s"             ,"Connected Line Identification Presentation %s %s"},
    {STR_MBPHONE_GSM_COLR           ,"被接线识别限制%s%s"               ,"Connected Line Identification Restriction %s %s"},
    {STR_MBPHONE_GSM_CLIR_INVOKE    ,"调用主叫号码显示限制%s"           ,"Activate Calling Line Identification Restriction %s"},
    {STR_MBPHONE_GSM_CLIR_SUPPRESS  ,"禁止主叫号码显示限制%s"           ,"Suppress Calling Line Identification Restriction %s"},
    {STR_MBPHONE_GSM_CLIP_NONE      ,"未提供服务"                       ,"unsupport"},
    {STR_MBPHONE_GSM_CLIP_ALLOW     ,"提供服务"                         ,"support "},
    {STR_MBPHONE_GSM_CLIP_UNKNOWN   ,"结果未知"                         ,"unknown"},
    {STR_MBPHONE_GSM_CLIR1          ,"未提供主叫号码显示限制服务"       ,"not provisioned"},
    {STR_MBPHONE_GSM_CLIR2          ,"以永久方式提供主叫号码显示限制服务","provisioned in permanent mode"},
    {STR_MBPHONE_GSM_CLIR3          ,"结果未知"                         ,"unknown (e.g. no network, etc."},
    {STR_MBPHONE_GSM_CLIR4          ,"主叫号码显示限制临时模式限制"     ,"temporary mode presentation restricted"},
    {STR_MBPHONE_GSM_CLIR5          ,"主叫号码显示限制临时模式允许"     ,"temporary mode presentation allowed"},
    {STR_MBPHONE_APPLY_FAIL         ,"请求遭拒"                         ,"Apply fail"},
    {STR_MBPHONE_CALLFORWARDING     ,">>"                               ,">>"},
    {STR_MBPHONE_QUICKDIAL_FAIL     ,"无记录"                           ,"No log"},
    {STR_MBRECORD_PRICE             ,"话费%s%s"                         ,"Cost %s %s"},
    {STR_MBRECORD_SET               ,"设置"                             ,"set"},
    {STR_MBRECORD_INPUTUNIT         ,"请输入单位话费"                   ,"Input unit"},
    {STR_MBRECORD_UNITERROR         ,"非法的单位话费"                   ,"Wrong unit"},
    {STR_MBRECORD_FARE_SETSUCC      ,"设置成功"                         ,"Set success"},
    {STR_MBRECORD_FARE_SETFAIL      ,"设置失败"                         ,"Set fail"},
    {STR_MBPHONE_HANGUPHOLD         ,"保持通话"                         ,"Hold"},
    {STR_MBPHONE_SHIFT              ,"转移"                             ,"Shift"},
    {STR_MBPHONE_MEETING            ,"电话会议"                         ,"Meeting"},
    {STR_MBPHONE_SINGLECALL         ,"单独通话"                         ,"Whisper"},
    {STR_MBPHONE_SINGLEHANGUP       ,"单独挂断"                         ,"Single hangup"},
    {STR_MBPHONE_CALLFORWARDINGSTART,"呼叫转移已启动"                   ,"Active divert"},
    {STR_MBPHONE_GSM_WRONGPASSWORD  ,"错误的密码"                       ,"Error code"},
    {STR_MBPHONE_USSD_DISCONNECT    ,"对方已断开连接"                   ,"Server has disconnected"},
    {STR_MBPHONE_USSD_LINKING       ,"正在发送请求，请稍侯"             ,"Sending request,waiting"},
    {STR_MBPHONE_USSD_REPLY         ,"回复"                             ,"Reply"},
    {STR_MBRECORD_PUK2ERROR         ,"PUK2码错误"                       ,"Error PUK2"},
    {STR_MBRECORD_INPUTPUK2         ,"请输入PUK2码"                     ,"Input PUK2"},
    {STR_MBRECORD_INPUTNEWPIN2      ,"请输入新PIN2码"                   ,"Input new PIN2"},
    {STR_MBRECORD_NEWPIN2CON        ,"确认PIN2码"                       ,"Confirm PIN2"},
    {STR_MBRECORD_CODECLEW          ,"密码不能为空"                     ,"Input the code"},
    {STR_MBRECORD_CONCODEERROR      ,"确认密码错误"                     ,"Affirm code error"},
    {STR_MBPHONE_CALLFORWARDINGUNSTART,"无条件呼叫转移已启动"           ,"Active CFU"},
    {STR_MBPHONE_MBWAIT_TITLE       ,"处理数据"                         ,"Deal Data"},
    {STR_MBPHONE_MBWAIT_STATE       ,"正在处理数据..."                  ,"Deal with data..."},
    {STR_MBPHONE_HANGUP_SINGLE      ,"挂断单个通话"                     ,"Hangup single"},
    {STR_MBPHONE_HANGUP_MEETING     ,"挂断电话会议"                     ,"Hangup meeting"},
    {STR_MBPHONE_CALLFORWARDING_CLEW,"转接来电"                         ,"Diverted call"},
    {STR_MBPHONE_GSM_BARRING_ERROR1 ,"服务未预定"                       ,"Requested service option not subscribed"},
    {STR_MBPHONE_GSM_BARRING_ERROR2 ,"密码错误"                         ,"Incorrect password"},
    {STR_MBPHONE_GSM_SUCC_1         ,"操作成功"                         ,"Operation succeed"},
    {STR_MBPHONE_GSM_FAIL_2         ,"操作失败"                         ,"Operation fail"},
    {STR_MBPHONE_GSM_FIND_FAIL      ,"查询失败"                         ,"Search fail"},
    {STR_MBPHONE_DIALLING_BARRING   ,"限制拨出"                         ,"Outgoing call barred"},
    {STR_MBPHONE_DIALLING_FARE      ,"已到话费限制"                     ,"Reach cost limit"},
    {STR_MBPHONE_HANGUP_CURRENTCALL ,"当前电话"                         ,"Current"},
    {STR_MBRECORD_COSTTYPE          ,"计费方式"                         ,"Show Cost"},
    {STR_MBRECORD_MONEY             ,"货币"                             ,"Money"},
    {STR_MBRECORD_UNIT              ,"单位"                             ,"Unit"},
    {STR_MBRECORD_UNITMONEY         ,"单位话费"                         ,"Unit money"},
    {STR_MBRECORD_MONEYUNIT         ,"货币单位"                         ,"Money unit"},
    {STR_MBRECORD_COSTSET           ,"话费限定"                         ,"Costs' limit"},
    {STR_MBRECORD_UNITLIMIT         ,"单位限额"                         ,"Unit limit"},
    {STR_MBRECORD_OPEN              ,"开"                               ,"On"},
    {STR_MBRECORD_CLOSE             ,"关"                               ,"Off"},
    {STR_MBRECORD_LASTCHARGE        ,"最后通话："                       ,"Last call:"},
    {STR_MBRECORD_TOTALCHARGE       ,"累计费用："                       ,"Total:"},
    {STR_MBRECORD_UNANSDWER_S       ,"%s %d个"                          ,"%s %d"},
    {STR_MBRECORD_UNANSDWER_M       ,"%s %d个"                          ,"%s %d"},
    {STR_MBRECORD_VIEW_CALLBACK     ,"回 叫"                            ,"Call"},
    {STR_MBPHONE_DIALUP             ,"拨 打"                            ,"Dialup"},
    {STR_MBPHONE_DIALNUMBER         ,"拨 号"                            ,"Dialup"},
    {STR_MBPHONE_RECORD_BEGIN       ,"录音"                             ,"Record"},
    {STR_MBPHONE_RECORD_END         ,"停止录音"                         ,"Stop"},
    {STR_MBPHONE_VIEW               ,"查看"                             ,"View"},
    {STR_MBPHONE_VIEW_LIST0         ,"记事本"                           ,"Notepad"},
    {STR_MBPHONE_VIEW_LIST1         ,"日程"                             ,"Calendar"},
    {STR_MBPHONE_VIEW_LIST2         ,"邮件"                             ,"Email"},
    {STR_MBPHONE_GSM_FORWARD_NO     ,"号码:"                            ,"no."},
    {STR_MBPHONE_CALLINGTIME        ,"通话时间:"                        ,"Call time:"},
    {STR_MBPHONE_GSM_BARRING_ERROR3 ,"非法的拨出号码"                   ,"Invalid dial string"},
    {STR_MBRECORD_AOC_INPUTCOINUNIT ,"请输入货币单位"                   ,"Input coin unit"},
    {STR_MBRECORD_INPUTUNITLIMIT    ,"请输入单位限额"                   ,"Input unit limit"},
    {STR_MBPHONE_USSD_NOSERVICE     ,"此项服务无效"                     ,"Without the service"},
    {STR_MBPHONE_EMERGENT           ,"紧急电话呼叫中..."                ,"Emergent calling..."},
    {STR_MBRECORD_MONDAY            ,"星期一"                           ,"Monday"},
    {STR_MBRECORD_TUESDAY           ,"星期二"                           ,"Tuesday"},
    {STR_MBRECORD_WEDNESDAY         ,"星期三"                           ,"Wednesday"},
    {STR_MBRECORD_THURSDAY          ,"星期四"                           ,"Thursday"},
    {STR_MBRECORD_FRIDAY            ,"星期五"                           ,"Firday"},
    {STR_MBRECORD_SATURDAY          ,"星期六"                           ,"Saturday"},
    {STR_MBRECORD_SUNDAY            ,"星期日"                           ,"Sunday"},
    {STR_MBRECORD_AM                ,"上午"                             ,"AM"},
    {STR_MBRECORD_PM                ,"下午"                             ,"PM"},
    {STR_MBPHONE_HANGUPEXT          ,"挂断"                             ,"Hangup"},
    {STR_MBPHONE_GSM_OPERATECANCEL  ,"操作取消"                         ,"Cancel operate!"},
    {STR_MBPHONE_REDIALCLEW         ,"第%d次重拨"                       ,"No. %d redial"},
    {STR_MBPHONE_INVALIDATENUMBER   ,"无效电话号码"                     ,"Invalid number"},
    {STR_MBPHONE_DTMFSENDING        ,"正在发送%s..."                    ,"Sending DTMF %s..."},
    {STR_MBPHONE_DTMFCONFIRM        ,"确定发送%s?"                      ,"Sending DTMF %s ?"},
    {STR_MBPHONE_INPUTDTMF          ,"请输入分机号:"                    ,"Input DTMF:"},
    {STR_MBRECORD_NODATATEXT        ,"无号码记录"                       ,"No number log."},
    {STR_MBPHONE_DONE               ,"完成!"                            ,"Finish!"},
    {STR_MBRECORD_FACE_UNIT         ,"单位"                             ,"Unit"},
    {-1,"",""}
};

extern  int             GetCurrentLanguage(void);
extern  unsigned char * GetString (int strID);
unsigned char * MBGetString(unsigned int index)
{
    unsigned int i = 0;

    while (MB_str[i].iStrID != -1)
    {
        if (index == MB_str[i].iStrID)
        {
            if (GetCurrentLanguage() == 1)//中文
                return (MB_str[i].MB_strChn);
            else//英文
                return (MB_str[i].MB_strEng);
        }
        i++;
    }
    return (GetString(index));
}
